/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AporritoRouteImport } from './routes/aporrito'
import { Route as EpikoinoniaRouteImport } from './routes/epikoinonia'
import { Route as ErgaEkdoseisRouteImport } from './routes/erga-ekdoseis'
import { Route as EtaireiaRouteImport } from './routes/etaireia'
import { Route as EtairikaStoixeiaRouteImport } from './routes/etairika-stoixeia'
import { Route as YpiresiesRouteImport } from './routes/ypiresies'
import { Route as ErgaleiaElegxosReadmeRouteImport } from './routes/ergaleia.elegxos-readme'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AporritoRoute = AporritoRouteImport.update({
  id: '/aporrito',
  path: '/aporrito',
  getParentRoute: () => rootRouteImport,
} as any)
const EpikoinoniaRoute = EpikoinoniaRouteImport.update({
  id: '/epikoinonia',
  path: '/epikoinonia',
  getParentRoute: () => rootRouteImport,
} as any)
const ErgaEkdoseisRoute = ErgaEkdoseisRouteImport.update({
  id: '/erga-ekdoseis',
  path: '/erga-ekdoseis',
  getParentRoute: () => rootRouteImport,
} as any)
const EtaireiaRoute = EtaireiaRouteImport.update({
  id: '/etaireia',
  path: '/etaireia',
  getParentRoute: () => rootRouteImport,
} as any)
const EtairikaStoixeiaRoute = EtairikaStoixeiaRouteImport.update({
  id: '/etairika-stoixeia',
  path: '/etairika-stoixeia',
  getParentRoute: () => rootRouteImport,
} as any)
const YpiresiesRoute = YpiresiesRouteImport.update({
  id: '/ypiresies',
  path: '/ypiresies',
  getParentRoute: () => rootRouteImport,
} as any)
const ErgaleiaElegxosReadmeRoute = ErgaleiaElegxosReadmeRouteImport.update({
  id: '/ergaleia/elegxos-readme',
  path: '/ergaleia/elegxos-readme',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aporrito': typeof AporritoRoute
  '/epikoinonia': typeof EpikoinoniaRoute
  '/erga-ekdoseis': typeof ErgaEkdoseisRoute
  '/etaireia': typeof EtaireiaRoute
  '/etairika-stoixeia': typeof EtairikaStoixeiaRoute
  '/ypiresies': typeof YpiresiesRoute
  '/ergaleia/elegxos-readme': typeof ErgaleiaElegxosReadmeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aporrito': typeof AporritoRoute
  '/epikoinonia': typeof EpikoinoniaRoute
  '/erga-ekdoseis': typeof ErgaEkdoseisRoute
  '/etaireia': typeof EtaireiaRoute
  '/etairika-stoixeia': typeof EtairikaStoixeiaRoute
  '/ypiresies': typeof YpiresiesRoute
  '/ergaleia/elegxos-readme': typeof ErgaleiaElegxosReadmeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aporrito': typeof AporritoRoute
  '/epikoinonia': typeof EpikoinoniaRoute
  '/erga-ekdoseis': typeof ErgaEkdoseisRoute
  '/etaireia': typeof EtaireiaRoute
  '/etairika-stoixeia': typeof EtairikaStoixeiaRoute
  '/ypiresies': typeof YpiresiesRoute
  '/ergaleia/elegxos-readme': typeof ErgaleiaElegxosReadmeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aporrito'
    | '/epikoinonia'
    | '/erga-ekdoseis'
    | '/etaireia'
    | '/etairika-stoixeia'
    | '/ypiresies'
    | '/ergaleia/elegxos-readme'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aporrito'
    | '/epikoinonia'
    | '/erga-ekdoseis'
    | '/etaireia'
    | '/etairika-stoixeia'
    | '/ypiresies'
    | '/ergaleia/elegxos-readme'
  id:
    | '__root__'
    | '/'
    | '/aporrito'
    | '/epikoinonia'
    | '/erga-ekdoseis'
    | '/etaireia'
    | '/etairika-stoixeia'
    | '/ypiresies'
    | '/ergaleia/elegxos-readme'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AporritoRoute: typeof AporritoRoute
  EpikoinoniaRoute: typeof EpikoinoniaRoute
  ErgaEkdoseisRoute: typeof ErgaEkdoseisRoute
  EtaireiaRoute: typeof EtaireiaRoute
  EtairikaStoixeiaRoute: typeof EtairikaStoixeiaRoute
  YpiresiesRoute: typeof YpiresiesRoute
  ErgaleiaElegxosReadmeRoute: typeof ErgaleiaElegxosReadmeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aporrito': {
      id: '/aporrito'
      path: '/aporrito'
      fullPath: '/aporrito'
      preLoaderRoute: typeof AporritoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epikoinonia': {
      id: '/epikoinonia'
      path: '/epikoinonia'
      fullPath: '/epikoinonia'
      preLoaderRoute: typeof EpikoinoniaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erga-ekdoseis': {
      id: '/erga-ekdoseis'
      path: '/erga-ekdoseis'
      fullPath: '/erga-ekdoseis'
      preLoaderRoute: typeof ErgaEkdoseisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etaireia': {
      id: '/etaireia'
      path: '/etaireia'
      fullPath: '/etaireia'
      preLoaderRoute: typeof EtaireiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etairika-stoixeia': {
      id: '/etairika-stoixeia'
      path: '/etairika-stoixeia'
      fullPath: '/etairika-stoixeia'
      preLoaderRoute: typeof EtairikaStoixeiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ypiresies': {
      id: '/ypiresies'
      path: '/ypiresies'
      fullPath: '/ypiresies'
      preLoaderRoute: typeof YpiresiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ergaleia/elegxos-readme': {
      id: '/ergaleia/elegxos-readme'
      path: '/ergaleia/elegxos-readme'
      fullPath: '/ergaleia/elegxos-readme'
      preLoaderRoute: typeof ErgaleiaElegxosReadmeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AporritoRoute: AporritoRoute,
  EpikoinoniaRoute: EpikoinoniaRoute,
  ErgaEkdoseisRoute: ErgaEkdoseisRoute,
  EtaireiaRoute: EtaireiaRoute,
  EtairikaStoixeiaRoute: EtairikaStoixeiaRoute,
  YpiresiesRoute: YpiresiesRoute,
  ErgaleiaElegxosReadmeRoute: ErgaleiaElegxosReadmeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
