/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ErgaEkdoseisRouteImport } from './routes/erga-ekdoseis'
import { Route as EtaireiaRouteImport } from './routes/etaireia'
import { Route as YpiresiesRouteImport } from './routes/ypiresies'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ErgaEkdoseisRoute = ErgaEkdoseisRouteImport.update({
  id: '/erga-ekdoseis',
  path: '/erga-ekdoseis',
  getParentRoute: () => rootRouteImport,
} as any)
const EtaireiaRoute = EtaireiaRouteImport.update({
  id: '/etaireia',
  path: '/etaireia',
  getParentRoute: () => rootRouteImport,
} as any)
const YpiresiesRoute = YpiresiesRouteImport.update({
  id: '/ypiresies',
  path: '/ypiresies',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/erga-ekdoseis': typeof ErgaEkdoseisRoute
  '/etaireia': typeof EtaireiaRoute
  '/ypiresies': typeof YpiresiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/erga-ekdoseis': typeof ErgaEkdoseisRoute
  '/etaireia': typeof EtaireiaRoute
  '/ypiresies': typeof YpiresiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/erga-ekdoseis': typeof ErgaEkdoseisRoute
  '/etaireia': typeof EtaireiaRoute
  '/ypiresies': typeof YpiresiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/erga-ekdoseis' | '/etaireia' | '/ypiresies'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/erga-ekdoseis' | '/etaireia' | '/ypiresies'
  id: '__root__' | '/' | '/erga-ekdoseis' | '/etaireia' | '/ypiresies'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ErgaEkdoseisRoute: typeof ErgaEkdoseisRoute
  EtaireiaRoute: typeof EtaireiaRoute
  YpiresiesRoute: typeof YpiresiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erga-ekdoseis': {
      id: '/erga-ekdoseis'
      path: '/erga-ekdoseis'
      fullPath: '/erga-ekdoseis'
      preLoaderRoute: typeof ErgaEkdoseisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etaireia': {
      id: '/etaireia'
      path: '/etaireia'
      fullPath: '/etaireia'
      preLoaderRoute: typeof EtaireiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ypiresies': {
      id: '/ypiresies'
      path: '/ypiresies'
      fullPath: '/ypiresies'
      preLoaderRoute: typeof YpiresiesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ErgaEkdoseisRoute: ErgaEkdoseisRoute,
  EtaireiaRoute: EtaireiaRoute,
  YpiresiesRoute: YpiresiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
